### ISSUE TITLE
Form Start | Get Quote - Form Viewed fires after Product Interaction event

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#109]
For the Get Quote Button, I am seeing the Form Viewed event firing after the Product Interaction Occurred event, which prevents form data from being sent on the server call. See screenshot below. 

![image](https://user-images.githubusercontent.com/83465286/124678249-c01cdb80-de87-11eb-9e77-cb06f31572b7.png)

@rmessickSDI , @jasonegan - I imagine this should be addressed in the data layer, but tagging you both in case it makes more sense to fix this on the launch.

**Comment by nate-wolfe** [comment]
@rmessickSDI, @jasonegan Will this be something that gets fixed in the data layer or in launch? These events were implemented in this order because semantically, the button press (Get Quote) happens before the form is viewed. If needed, I can fire "Product Interaction Occurred" here on a delay to place it after "Form Viewed", but it may be more elegant to solve this in Launch if possible.

**Comment by rmessickSDI** [comment]
Added the form view to send its own beacon call.  I think this will solve this.

**Comment by ryanAtSdi** [comment]
Confirming this is resolved now:
![image](https://user-images.githubusercontent.com/83465286/124791980-31a16c00-df12-11eb-9cf3-fc0639cdfacb.png)
