### ISSUE TITLE
Navigation Link Clicked - Analytics Beacon

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#14]
When clicking an analytics beacon, the data layer looks okay:
![image](https://user-images.githubusercontent.com/72522616/114074200-1f138a00-9872-11eb-9d9b-f0f626a4d50c.png)

However, the eVars 32, 33 and 51 are hot being populated in the beacon:
![image](https://user-images.githubusercontent.com/72522616/114074417-58e49080-9872-11eb-96c8-e157aa1ce868.png)

You can see event38 firing there as it should be.

**Comment by rmessickSDI** [comment]
@savithanuguri This issue is from the `link` but should be `linkInfo`

https://github.com/searchdiscovery/mohawk-flooring-dl-spec/blob/main/events/Navigation%20Link%20Clicked.md

Also this Looks like data is not populating correctly.  
![image](https://user-images.githubusercontent.com/78565036/115061496-df225780-9eae-11eb-9017-8e8115784eb7.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/115329774-cc36ae00-a160-11eb-89db-6b2d06082526.png)

**Comment by rmessickSDI** [comment]
![Uploading image.png…]()
