### ISSUE TITLE
Visualizer Viewed - Event not in data layer on standalone page

### ISSUE THREAD

**Issue by ryanAtSdi** [searchdiscovery/mohawk-flooring-dl-spec#78]
On the visualizer page (https://staging.pergoflooring.com/discover/visualizer?collection=Pergo%20TimberCraft%20%2BWetProtect&productType=Laminate%20Wood), no visualizer viewed event (e15) is fired in data layer:
![image](https://user-images.githubusercontent.com/83465286/118553023-5e60b080-b725-11eb-80c8-a81cc8f25bd4.png)

**Comment by savithanuguri** [comment]
![image](https://user-images.githubusercontent.com/82102160/119353755-49c67000-bc71-11eb-8966-194be07df76f.png)
@ryanAtSdi , please test in Staging

**Comment by ryanAtSdi** [comment]
@savithanuguri - I see it there now as well. Thank you!

@rmessickSDI , @jasonegan - assigning this over to you, as there is no Visualizer Viewed beacon call on the stand-alone visualizer page.

**Comment by rmessickSDI** [comment]
@savithanuguri On the initial page load `Visualizer Viewed` does not load but on page refresh it does.  
![image](https://user-images.githubusercontent.com/78565036/119500574-91aacd00-bd2d-11eb-8fbe-b3b930414556.png)

Also looking at PDP it should fire when use clicks on visualize tab.  https://staging.pergoflooring.com/shop/laminate/outlast/detail/LF000850/antique-cherry%3Ftitle%3DPergo%2520Outlast%2B%2520with%2520SpillProtect&expand%3Ddescription?tab=visualizer

I am bringing this up since we need it to be consistent on does it happen **before** `Page Load Complete` or **after**.  Since the PDP page it will happen **after** the `Page Load Complete` can we also have the stand-alone page fire it **after** the `Page Load Completed`?

CC @ryanAtSdi @jasonegan

**Comment by nate-wolfe** [comment]
![image](https://user-images.githubusercontent.com/81365619/121379731-50601300-c912-11eb-9312-bd6fff4b6440.png)

Loads on initial page load now, and on the Visualize It PDP tab.

**Comment by ryanAtSdi** [comment]
@nate-wolfe , @savithanuguri - I see the even now, but a few questions:

1. When a user selects a different flooring type (ex: clicks Hardwood), should the full list of new product strings be sent? Currently, when a different flooring type is clicked, only the first item is sent, so I wanted to ensure that was expected behavior.
2. Should v67 be a more user-friendly name, such as Kitchen, Bedroom, etc.? Right now, it's a code/ID sent through.

![image](https://user-images.githubusercontent.com/83465286/121398584-219a6a80-c91b-11eb-8431-489164d1f2cb.png)

**Comment by ryanAtSdi** [comment]
@nate-wolfe , @savithanuguri - just wanted to follow up on the above.

**Comment by nate-wolfe** [comment]
@ryanAtSdi The value showing in the screenshot is a unique key to uniquely identify the image used and product selected. After discussing with Savitha, it appears this is correct. That said, we cannot access this value from the PDP, only the standalone visualizer, so the PDP visualizer has to follow a different format.

**Comment by ryanAtSdi** [comment]
Thank you, @nate-wolfe! I'll close this ticket out then.
